// Generated by gencpp from file environment_controller/use_keyResponse.msg
// DO NOT EDIT!


#ifndef ENVIRONMENT_CONTROLLER_MESSAGE_USE_KEYRESPONSE_H
#define ENVIRONMENT_CONTROLLER_MESSAGE_USE_KEYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace environment_controller
{
template <class ContainerAllocator>
struct use_keyResponse_
{
  typedef use_keyResponse_<ContainerAllocator> Type;

  use_keyResponse_()
    : success(false)  {
    }
  use_keyResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::environment_controller::use_keyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::environment_controller::use_keyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct use_keyResponse_

typedef ::environment_controller::use_keyResponse_<std::allocator<void> > use_keyResponse;

typedef boost::shared_ptr< ::environment_controller::use_keyResponse > use_keyResponsePtr;
typedef boost::shared_ptr< ::environment_controller::use_keyResponse const> use_keyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::environment_controller::use_keyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::environment_controller::use_keyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::environment_controller::use_keyResponse_<ContainerAllocator1> & lhs, const ::environment_controller::use_keyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::environment_controller::use_keyResponse_<ContainerAllocator1> & lhs, const ::environment_controller::use_keyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace environment_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::environment_controller::use_keyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::environment_controller::use_keyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::environment_controller::use_keyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::environment_controller::use_keyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment_controller::use_keyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::environment_controller::use_keyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::environment_controller::use_keyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::environment_controller::use_keyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::environment_controller::use_keyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "environment_controller/use_keyResponse";
  }

  static const char* value(const ::environment_controller::use_keyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::environment_controller::use_keyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::environment_controller::use_keyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::environment_controller::use_keyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct use_keyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::environment_controller::use_keyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::environment_controller::use_keyResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ENVIRONMENT_CONTROLLER_MESSAGE_USE_KEYRESPONSE_H
