// Generated by gencpp from file simple_control/toggle_geofence.msg
// DO NOT EDIT!


#ifndef SIMPLE_CONTROL_MESSAGE_TOGGLE_GEOFENCE_H
#define SIMPLE_CONTROL_MESSAGE_TOGGLE_GEOFENCE_H

#include <ros/service_traits.h>


#include <simple_control/toggle_geofenceRequest.h>
#include <simple_control/toggle_geofenceResponse.h>


namespace simple_control
{

struct toggle_geofence
{

typedef toggle_geofenceRequest Request;
typedef toggle_geofenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct toggle_geofence
} // namespace simple_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simple_control::toggle_geofence > {
  static const char* value()
  {
    return "08263b5cc812a6e30c6226c22efcab08";
  }

  static const char* value(const ::simple_control::toggle_geofence&) { return value(); }
};

template<>
struct DataType< ::simple_control::toggle_geofence > {
  static const char* value()
  {
    return "simple_control/toggle_geofence";
  }

  static const char* value(const ::simple_control::toggle_geofence&) { return value(); }
};


// service_traits::MD5Sum< ::simple_control::toggle_geofenceRequest> should match
// service_traits::MD5Sum< ::simple_control::toggle_geofence >
template<>
struct MD5Sum< ::simple_control::toggle_geofenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simple_control::toggle_geofence >::value();
  }
  static const char* value(const ::simple_control::toggle_geofenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_control::toggle_geofenceRequest> should match
// service_traits::DataType< ::simple_control::toggle_geofence >
template<>
struct DataType< ::simple_control::toggle_geofenceRequest>
{
  static const char* value()
  {
    return DataType< ::simple_control::toggle_geofence >::value();
  }
  static const char* value(const ::simple_control::toggle_geofenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simple_control::toggle_geofenceResponse> should match
// service_traits::MD5Sum< ::simple_control::toggle_geofence >
template<>
struct MD5Sum< ::simple_control::toggle_geofenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simple_control::toggle_geofence >::value();
  }
  static const char* value(const ::simple_control::toggle_geofenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_control::toggle_geofenceResponse> should match
// service_traits::DataType< ::simple_control::toggle_geofence >
template<>
struct DataType< ::simple_control::toggle_geofenceResponse>
{
  static const char* value()
  {
    return DataType< ::simple_control::toggle_geofence >::value();
  }
  static const char* value(const ::simple_control::toggle_geofenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMPLE_CONTROL_MESSAGE_TOGGLE_GEOFENCE_H
